### ISSUE TITLE
[BUG] Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor

### ISSUE THREAD

**Issue by jaschenk** [rzwitserloot/lombok#2790]
Issue during Java build using JDK 14 and Lombok 1.18.18:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project a-service: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x363d3958) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x363d395**

?

**Comment by jaschenk** [comment]
Issue resolved due to build platform including incorrect image.

**Comment by abhishekdanej** [comment]
Hi, I'm using Java 16 and Spring Boot 2.4.4 and still getting the error. Is there anything I could do? I was earlier running same code on Java 11 and it worked fine. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project ybl-oastatusreport-spring-boot: Fatal
error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x5875de6a) cannot access class com.sun.tools.javac.processin
g.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x5875de6a -> [Help
 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) o
n project ybl-oastatusreport-spring-boot: Fatal error compiling
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

**Comment by Rawi01** [comment]
This should work if you use lombok 1.18.20

**Comment by mariiamamr** [comment]
> This should work if you use lombok 1.18.20

can you tell us why this occur

**Comment by Rawi01** [comment]
JDK 16 uses strong encapsulation by default. Lombok have to use compiler internal classes to modify things during compilation. Since 1.18.20 lombok uses a workaround/hack to still access these classes but this most likely will not be possible anymore in future versions (it still works fine in JDK17). As soon as this happens you have to add a bunch of additional `--add-opens` flags. You can find some more details in #2681.

**Comment by mariiamamr** [comment]
I have a problem I worked with java 8 and lombok 1.18.10 cannot compile but when I updated the version it worked well but I don't have access to change the version in the remote repo so do you know an alternative solution?

**Comment by mariiamamr** [comment]
or why lombok 1.18.10 gives fatal compilation error

**Comment by rzwitserloot** [comment]
@mariiamamr There is no solution. Upgrade lombok or downgrade java.

**Comment by mariiamamr** [comment]
Okay will do that, thanks for the clarification.
