### ISSUE TITLE
Generic @Delegate incompatible with @NonNull (stopped working in 1.18.4)

### ISSUE THREAD

**Issue by hosswald** [rzwitserloot/lombok#1935]
In Lombok 1.18.4, ~~the following does not compile~~ [(see updated example)](https://github.com/rzwitserloot/lombok/issues/1935#issuecomment-438069655)
```
public class MyWrapper<T> implements Iterable<T> {
    @Delegate
    private final Iterable<T> data;
}
```
I get the following error:
```
error: @Delegate can only use concrete class types, not wildcards, arrays, type variables, or primitives.
    @Delegate
    ^
1 error
```
In 1.18.2 it worked.

**Comment by rzwitserloot** [comment]
Took that exact code, tried it with javac 8, 11, and the beta 12. Cannot reproduce, with the latest master branch lombok (which for this regard should be equivalent to 1.18.4, we haven't changed anything that would be anywhere near this).

Something else must be the problem here.

**Comment by hosswald** [comment]
@rzwitserloot Sorry, I just realized I missed something when I wrote the minimal example. The `@Delegate` is also marked `@NonNull`:
```
import lombok.NonNull;
import lombok.experimental.Delegate;

public class MyWrapper<T> implements Iterable<T> {
  @Delegate
  @NonNull
  private final Iterable<T> data;
}
```

```
$ javac -version
javac 1.8.0_181

$ javac -cp lombok.jar MyWrapper.java
MyWrapper.java:5: error: @Delegate can only use concrete class types, not wildcards, arrays, type variables, or primitives.
  @Delegate
  ^
1 error
```
lombok.jar being 1.18.4.
You should be able to reproduce this.

**Comment by hosswald** [comment]
Please re-open, @rzwitserloot.

**Comment by rspilker** [comment]
According to a friend of mine, it occurs in java8 but not in java11.

**Comment by rspilker** [comment]
Reproduced it using java8 and confirmed that java11 does not contain this bug.

**Comment by lukashinsch** [comment]
Thanks for fixing. When will this be available to test in edge-SNAPSHOT?

**Comment by pengsoftdotcom** [comment]
This error occurs again in version 1.18.6, also using Java 11.
Here is my code.
`
public class JpaBeanServiceImpl<R extends JpaBeanRepository<Q, T>, Q extends EntityPathBase<T>, T extends Beanable>
        implements BeanService<T> {

    @Delegate
    @Inject
    private R repository;
}
`

**Comment by umeshTW** [comment]
is this bug is fixed , still having the same with java 8 + 1.18.6 lombok
