### ISSUE TITLE
1.16.20 Not working in NetBeans due to NoClassDefFoundError

### ISSUE THREAD

**Issue by AlexFalappa** [rzwitserloot/lombok#1592]
In a maven project using Spring Boot 1.5.10.RELEASE which depends on Lombok 1.16.20 the lombok annotated classes do not get processed and I have no synthesized accessor methods.

A warning tooltip reveals a `NoClassDefFoundError` in lombok processing pipeline:
![noclassdeffound](https://user-images.githubusercontent.com/1875690/36666187-2067dc66-1aea-11e8-961d-f7340af37e67.png)

**Comment by AlexFalappa** [comment]
For the record this was observed on NetBeans 8.1 running on Oracle JDK 8

**Comment by AlexFalappa** [comment]
Verified it doesn't occur with **NetBeans 8.2** running on the same **Oracle JDK 8** and corrected the issue title accordingly

**Comment by pokebadgerswithspoon** [comment]
Does not work with 8.2 either.
No stacktrace is available, nor modified class is in target/classes/ . If lombok is excluded from dependency list, then modified class appears where it should be.

**Comment by AlexFalappa** [comment]
@pokebadgerswithspoon I experienced your issue on NetBeans 8.2 but it is a bit different than this.

On NetBeans 8.2 the IDE is aware of Lombok synthetic methods (they show up in the Navigator view and autocompletion) what's left is the bad behaviour of compile on save reported in #1577 (that by the way causes malfunction of devtools restart feature).

On NetBeans 8.1 the IDE is not even aware of Lombok synthetic methods (they don't show up neither in Navigator view nor in autocompletion) I haven't tried to verify the compile on save behaviour.

What I am supposing is that the root cause of this issue and #1577 might be the same.
