### ISSUE TITLE
[BUG] Compilation with Groovy-Eclipse + Lombok 1.18.16 from IntelliJ IDEA fails

### ISSUE THREAD

**Issue by kriegaex** [rzwitserloot/lombok#2735]
**Describe the bug**
Compiling Java files containing Lombok annotations fails with `NoClassDefFoundError: lombok/launch/PatchFixesHider$Transform` in IDEA.

**To Reproduce**
Set up Java project (mine uses Maven) and then configure IDEA like this:

![image](https://user-images.githubusercontent.com/1537384/106557811-31610700-6555-11eb-9e3d-f03b1651a1e7.png)

![image](https://user-images.githubusercontent.com/1537384/106557740-0c6c9400-6555-11eb-8fe1-6d3924b491d3.png)

Then compile a Java file with Lombok annotations. There will be a build error:

```text
Groovy-Eclipse: Error: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilationInner(GreclipseBuilder.java:263)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilation(GreclipseBuilder.java:220)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.build(GreclipseBuilder.java:171)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1441)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1100)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1224)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1066)
	at org.jetbrains.jps.incremental.IncProjectBuilder.access$1200(IncProjectBuilder.java:67)
	at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer$1.run(IncProjectBuilder.java:1006)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: lombok/launch/PatchFixesHider$Transform
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11624)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12813)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13037)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12994)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11385)
	at org.codehaus.jdt.groovy.integration.internal.MultiplexingParser.dietParse(MultiplexingParser.java:47)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:862)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:404)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:458)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:436)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4764)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1777)
	... 21 more
Caused by: java.lang.ClassNotFoundException: lombok.launch.PatchFixesHider$Transform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

**Expected behavior**
IDEA should compile Java + Lombok classes without errors, just like Javac does with the exact same classes if I just switch the Java compiler to Javac in IDEA.

**Version info (please complete the following information):**
 - Lombok 1.18.16
 - Groovy-Eclipse Batch 2.5.12-02, Groovy-Eclipse Compiler 3.6.0-03

See also https://youtrack.jetbrains.com/issue/IDEA-260789

**Comment by Rawi01** [comment]
I think the `NoClassDefFoundError` mentioned in the IDEA bugtracker is the actual root cause here. Can you try if it works in 1.18.10?

**Comment by kriegaex** [comment]
> I think the `NoClassDefFoundError` mentioned in the IDEA bugtracker is the actual root cause here.

You mean the one I mentioned here in more detail, don't you? Because it is the same as in the IDEA bugtracker, as far as I can see.

> Can you try if it works in 1.18.10?

No, it does not. I also tried 1.18.12, same result.

**Comment by Rawi01** [comment]
@kriegaex The exception in the linked issue is in `lombok.launch.PatchFixesHider$Transform.<clinit>` (thats the name for the static initialization). As that one does not work the whole class is not there and thats why it throws an almost similar exception later on. I already have a rough idea what the problem could be, most likely I broke that one by referencing eclipse only dependencies in the normal `ecj` code path.

**Comment by kriegaex** [comment]
Thank you for taking care of this issue. Is there a development build for me to test?

**Comment by kriegaex** [comment]
I just cloned the project and built the current master, which was quite time-consuming because I normally never use Ant or Ivy, only Maven. So the project downloaded all dependencies to a local Ivy cache instead of using the local Maven repository. Anyway, the built went smoothly with target `lombok.compile.dist`.

Then I used the resulting artifact from both Maven (copied it to the appropriate place in the local repo) and IntelliJ IDEA as shown in the screenshots. No change, same stack trace. So please reopen this issue, it is not fixed.

**Comment by Rawi01** [comment]
Have you also added lombok.jar to the bootclasspath (`-Xbootclasspath/a:/path/to/lombok.jar`)? I just tried my super simple example project and it works there.

**Comment by kriegaex** [comment]
With `-Xbootclasspath/a:` it works. I was unaware of the fact that that was necessary. Thanks for the hint.

The ugly remaining issue in IDEA is that when importing my Surefire or Failsafe settings from Maven, IDEA will recognise


```xml
<compilerArguments>
  <javaAgentClass>lombok.launch.Agent</javaAgentClass>
</compilerArguments>
```

and convert it to this invalid Groovy-Eclipse parameter:

![image](https://user-images.githubusercontent.com/1537384/110093782-ae3e0580-7dcd-11eb-91c0-964dbf14c888.png)

After each auto-import I have to remove it again.

**Comment by Rawi01** [comment]
I agree that this is annoying but thats something that has to be changed in IntelliJ and not in lombok itself.

**Comment by kriegaex** [comment]
Actually, this workaround does not seem to be stable, because now when I use the previously working `-Xbootclasspath/a:c:\Users\Alexa\.m2\repository\org\projectlombok\lombok\1.18.19-SNAPSHOT\lombok-1.18.19-SNAPSHOT.jar
-javaagent:c:\Users\Alexa\.m2\repository\org\projectlombok\lombok\1.18.19-SNAPSHOT\lombok-1.18.19-SNAPSHOT.jar=ECJ` or the latest release `-Xbootclasspath/a:c:\Users\Alexa\.m2\repository\org\projectlombok\lombok\1.18.20\lombok-1.18.20.jar
-javaagent:c:\Users\Alexa\.m2\repository\org\projectlombok\lombok\1.18.20\lombok-1.18.20.jar=ECJ`, it still is not working. I tried JDK 13 and 16. The error is always the same, but this time a different class is not found, which is somewhat surprising, because it is a bootstrap class which exists in the JRE: `java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor`

```none
Groovy-Eclipse: Error: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilationInner(GreclipseBuilder.java:261)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilation(GreclipseBuilder.java:226)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.build(GreclipseBuilder.java:169)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1485)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1123)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1268)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1088)
	at org.jetbrains.jps.incremental.IncProjectBuilder.access$1200(IncProjectBuilder.java:69)
	at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer$1.run(IncProjectBuilder.java:1028)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1257)
	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2199)
	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:118)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:661)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:637)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BatchAnnotationProcessorManager.discoverNextProcessor(BatchAnnotationProcessorManager.java:177)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:119)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotationsInternal(Compiler.java:970)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:944)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:460)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:436)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4764)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1777)
	... 21 more
Errors occurred while compiling module 'geb-spock-samples-mockito'
Errors occurred while compiling module 'geb-spock-samples-powermock'
Searching for compilable files... [tests of geb-spock-samples-mockito]
Searching for compilable files... [tests of geb-spock-samples-powermock]
Compiling java & groovy [tests of geb-spock-samples-mockito]
Searching for compilable files... [tests of geb-spock-samples]
Compiling java & groovy [tests of geb-spock-samples-powermock]
Compiling java & groovy [tests of geb-spock-samples]
Groovy-Eclipse: Error: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilationInner(GreclipseBuilder.java:261)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilation(GreclipseBuilder.java:218)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.build(GreclipseBuilder.java:169)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1485)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1123)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1268)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1088)
	at org.jetbrains.jps.incremental.IncProjectBuilder.access$1200(IncProjectBuilder.java:69)
	at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer$1.run(IncProjectBuilder.java:1028)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1257)
	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2199)
	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:118)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:661)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:637)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BatchAnnotationProcessorManager.discoverNextProcessor(BatchAnnotationProcessorManager.java:177)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:119)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotationsInternal(Compiler.java:970)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:944)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:460)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:436)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4764)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1777)
	... 21 more
```

**Comment by CaCoCa** [comment]
I am experiencing the same problem, has it been fixed please? Or how to fix this problem
