### ISSUE TITLE
Gradle 4.9 + lombok 1.18 = build failed

### ISSUE THREAD

**Issue by Alexuy** [rzwitserloot/lombok#1782]
Now lombok not comatible with gradle 4.9. Please, fix it

**Comment by rspilker** [comment]
Can you test this using the [edge release](https://projectlombok.org/download-edge)? Although not mentioned in the changelog, we did improve gradle support.

**Comment by rspilker** [comment]
Can you test this using the [edge release](https://projectlombok.org/download-edge)? Although not mentioned in the changelog, we did improve gradle support.

**Comment by pun-ky** [comment]
I have also tested and could confirm that 1.18.0 and 1.16.22 is not working with Gradle 4.8
e.g when I add to my class XXX annotation @Builder then occurred compilation error "Cannot find symbol XXXBuilder" but if I downgrade to Gradle 4.6, the code is being compiled correctly.

 I am convinced that Lombok should be aligned to recent version of Gradle.

**Comment by renannprado** [comment]
for whoever is also running in this issue:

In the the [gradle tutorial in the oficial website](https://projectlombok.org/setup/gradle) it uses older version of the `net.ltgt.apt` plugin, which was causing my gradle4.9+java10 build to fail.

Upgrading `net.ltgt.apt` plugin to version `0.18` fixed the problem.

Ref:

![image](https://user-images.githubusercontent.com/2359543/43530430-d37b81fc-95ad-11e8-9d4a-f0a46005b01b.png)

**Comment by methinks** [comment]
Thanks, it does indeed.
