### PR TITLE
Fix compilation using ecj

### LINKED ISSUE #285: lombok should run flawlessly as agent in ecj environment. Lombok as AP in ecj is broken.
_Migrated from Google Code (issue 212)_

### LINKED ISSUE #2633: [BUG] Regression: #2006 breaks Delegate in Tycho
**Describe the bug**
Inclusion of the new method PatchDelegate.getChildren(IJavaElement[], SourceTypeElementInfo) from #2006 and according implementation with imports from org.eclipse.jdt.internal.core break compatibility with Tycho (which uses ECJ, didn't test with plain ECJ) because the packages are not available there. 
Loading from lombok.eclipse.agent.PatchDelegatePortal.Reflection throws ClassNotFoundExceptions (with -Dlombok.debug.reflection=true).
Thus @Delegate doesn't work at all with the latest Lombok on Tycho.

**To Reproduce**
Reproduction would need my changes for Tycho, but should be reproducable with ECJ only as well.

**Expected behavior**
Delegates should be working on Tycho/ECJ as well.

**Version info (please complete the following information):**
 - 1.18.16
 - Tycho/ECJ >=1.5.0

**Additional context**
@Rawi01 I think it should work if you can put the additions to a new class and load it seperately in PatchDelegatePortal.

Wouldn't it be good to show the Exceptions when Delegate is actually used. Swallowing makes sense when it's not used, but in this case it took me a long time to figure out what was wrong because I didn't see the exception without the lombok.debug.reflection switch.

### LINKED ISSUE #2640: [Regression] Exception when compiling GWT application with Lombok 1.18.16
We have been using Lombok in our GWT application for years now by using the following setting in the gwt-maven-plugin:

`<extraJvmArgs>-javaagent:${lombok.jar.path}=ECJ</extraJvmArgs>`

SuperDevMode also works when giving the same JVM parameter on launch. However, when I try to update to Lombok 1.18.16, I get the following error during the GWT compilation (repeated many times), and the compilation fails:

```
Lombok annotation handler class lombok.eclipse.handlers.HandleGetter failed
java.lang.NoClassDefFoundError: org.eclipse.core.runtime.PlatformObject
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:942)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:535)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:338)
	at lombok.eclipse.handlers.EclipseHandlerUtil.eclipseMode(EclipseHandlerUtil.java:2672)
	at lombok.eclipse.handlers.EclipseHandlerUtil.setDocComment(EclipseHandlerUtil.java:2686)
	at lombok.eclipse.handlers.EclipseHandlerUtil.copyJavadoc(EclipseHandlerUtil.java:2797)
	at lombok.eclipse.handlers.EclipseHandlerUtil.copyJavadoc(EclipseHandlerUtil.java:2764)
	at lombok.eclipse.handlers.HandleGetter.createGetter(HandleGetter.java:299)
	at lombok.eclipse.handlers.HandleGetter.createGetterForField(HandleGetter.java:224)
	at lombok.eclipse.handlers.HandleGetter.generateGetterForField(HandleGetter.java:134)
	at lombok.eclipse.handlers.HandleGetter.generateGetterForType(HandleGetter.java:105)
	at lombok.eclipse.handlers.HandleGetter.handle(HandleGetter.java:161)
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:267)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:107)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:233)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:233)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:226)
	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:224)
	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:185)
	at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:110)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:119)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:190)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:9959)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11136)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11360)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11317)
	at com.google.gwt.dev.javac.JdtCompiler$ParserImpl.parse(JdtCompiler.java:229)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:9732)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:809)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:385)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:428)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1040)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:213)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:192)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:151)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:104)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:666)
	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:810)
	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:551)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:913)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
	at com.google.gwt.dev.DevMode.main(DevMode.java:432)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.runtime.PlatformObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	... 104 more
```
When reverting to Lombok 1.18.12 the problem goes away again.

I tried creating a minimal example, but have not managed to reproduce the issue yet with a minimal GWT application. Maybe someone has an idea about what might cause it anyway, otherwise I'll put in more effort to try creating a reproduction case.

### LINKED ISSUE #2729: ECJ + Bump lombok from 1.18.16 to 1.18.18 = Unknown source: java.lang.IllegalArgumentException: argument type mismatch
**Describe the bug**
Bumping lombok from 1.18.16 to 1.18.18 on project compiled with maven using ecj causes following
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project will: Compilation failure
Error:  Unknown source: java.lang.IllegalArgumentException: argument type mismatch
```

Upgraded lombok works fine in the same project when compiled with javac.

**To Reproduce**
https://github.com/pzrep/lombok-2729
with upgrade failed in https://github.com/pzrep/lombok-2729/pull/5

**Expected behavior**
Build completed with success.

**Version info (please complete the following information):**
 - 1.18.18
 - maven + plexus-compiler-eclipse + org.eclipse.jdt:ecj:3.24.0

### LINKED ISSUE #2735: [BUG] Compilation with Groovy-Eclipse + Lombok 1.18.16 from IntelliJ IDEA fails
**Describe the bug**
Compiling Java files containing Lombok annotations fails with `NoClassDefFoundError: lombok/launch/PatchFixesHider$Transform` in IDEA.

**To Reproduce**
Set up Java project (mine uses Maven) and then configure IDEA like this:

image

image

Then compile a Java file with Lombok annotations. There will be a build error:

```text
Groovy-Eclipse: Error: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilationInner(GreclipseBuilder.java:263)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilation(GreclipseBuilder.java:220)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.build(GreclipseBuilder.java:171)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1441)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1100)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1224)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1066)
	at org.jetbrains.jps.incremental.IncProjectBuilder.access$1200(IncProjectBuilder.java:67)
	at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer$1.run(IncProjectBuilder.java:1006)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: lombok/launch/PatchFixesHider$Transform
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11624)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12813)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13037)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12994)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11385)
	at org.codehaus.jdt.groovy.integration.internal.MultiplexingParser.dietParse(MultiplexingParser.java:47)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:862)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:404)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:458)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:436)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4764)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1777)
	... 21 more
Caused by: java.lang.ClassNotFoundException: lombok.launch.PatchFixesHider$Transform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

**Expected behavior**
IDEA should compile Java + Lombok classes without errors, just like Javac does with the exact same classes if I just switch the Java compiler to Javac in IDEA.

**Version info (please complete the following information):**
 - Lombok 1.18.16
 - Groovy-Eclipse Batch 2.5.12-02, Groovy-Eclipse Compiler 3.6.0-03

See also https://youtrack.jetbrains.com/issue/IDEA-260789

### LINKED ISSUE #2738: [BUG] Intellij IDEA 2020.3.2 AND 2020.2.4 + lombok 1.18.18 illegalArgumentException
**Describe the bug**
Play Framework 1 project works with Intellij IDEA 2020.2.4 + lombok 1.18.10. Upgrading to Intellij IDEA 2020.3.2 means we need to upgrade lombok. Neither 1.18.16 work (LOTS of errors during runtime), nor 1.18.18 (illegalArgumentException during runtime).
compiler is set to javac in IDEA, run options are
`-Dapplication.path="."  -javaagent:lib\lombok-1.18.10.jar -Xverify:none`

Also, quite important IMHO: We get the same issues with IDEA 2020.2.4 + lombok 1.18.18, so it's definitely an issue on lomboks end.

**To Reproduce**
Getting stack traces for several totally unrelated plugins, even cusom made ones, but they all look the same;

```
09:59:17,566 play.Logger ERROR ~ Error loading plugin LoadingPluginInfo{name='press.Plugin', index=100, url=file:/[redacted]/application/local-modules/press-1.0.36/app/play.plugins}
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:126)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:203)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:10525)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11706)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11930)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11887)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:10297)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:840)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:394)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:444)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:314)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:315)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:172)
	at play.classloading.ApplicationClassloader.loadClass(ApplicationClassloader.java:90)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at play.plugins.PluginCollection.loadPlugins(PluginCollection.java:173)
	at play.Play.init(Play.java:320)
	at play.server.Server.main(Server.java:162)

```

**Expected behavior**
Everything works

**Version info:**
 - 1.18.18
 - Intellij IDEA BOTH 2020.2.4 AND 2020.3.2, javac 11.0.9, Windows 10, AdoptOpenJDK 11 latest

### PR DESCRIPTION
**Pull request by Rawi01**
This PR fixes #2738, fixes #2735, fixes #2729, fixes #2640, fixes #2633, fixes #285

The first commit moves all Eclipse only methods into a seperate inner class which only gets touched if Eclipse is available. I also tried to simplify the code. Basically this is a simpler version of #2634 that does not break the detection of already implemented methods.

The second commit solves the classloading problem by
- changing `ShadowClassLoader` to reuse classes of the prepended classloader instead of creating a new ones
- removing all direct references to `ecj` classes in ecj related methods in `PatchFixesHider`. As the `Patch*` classes get loaded by `ShadowClassLoader` they also use it for resolving all the ecj classes.
- using `transplant()` for `skipResolveInitializerIfAlreadyCalled(2)`. That is required because casting of the returned `TypeBinding` is not possible for method replacements.

I also removed the `PatchExtensionMethodPortal` because it was not used at all.

These changes are inspired a lot by https://github.com/rgra/lombok/commit/6503177f7b73d14114eaf0585dbb5c25039ae1c8 from @rgra, thanks a lot for that and the tycho example project.

### CODE REVIEW

**Comment by pzygielo** [comment]
Could this change deserve new edge build?
