### ISSUE TITLE
Spring Boot upgrade from 2.3.4 to 2.4 results in Test Package Entity build failures

### ISSUE THREAD

**Issue by cobar79** [rzwitserloot/lombok#2660]
When upgrading from Spring Boot 2.3.4 to 2.4, the test classes referencing @Entity classes using lombok annotations won't compile.

**To Reproduce**
`    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.4.RELEASE</version>
        <relativePath/> 
    </parent>
`
`
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.0</version>
        <relativePath/> 
    </parent>
`
`
@Getter
@Setter
@ToString
@NoArgsConstructor
@Entity
public class DsrcCode implements Serializable {
...............
`
`
$ mvn test
java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException:
Uncompilable source code - cannot find symbol
  symbol:   class DsrcCode
  location: package com.foobar.entity
`

**Expected behavior**
Test classes referencing Entity classes should be found and compile when using lombok annotations

**Version info (please complete the following information):**
 - Lombok version 1.18.12
 - Platform jdk8

**Additional context**
IDE also shows it can't find entity in the test classes.

**Comment by rzwitserloot** [comment]
This sounds like a bug you should be filing with spring boot. If it's a lombok problem, your reproduction formula is incomplete. There is no source to run or test. I don't use Spring Boot, that may help to explain why this mystifies me.
