### ISSUE TITLE
@Builder with generics does not compile but delomboked code does

### ISSUE THREAD

**Issue by udalrich** [rzwitserloot/lombok#1298]
This class

    import java.util.Set;
    import lombok.Builder;
    import lombok.Value;

    interface Inter<T, U extends Inter<T,U>> {}

    @Builder
    @Value
    public class Test<Foo,
			  Bar extends Set<Foo>,
				      Quz extends Inter<Bar, Quz>>  {

	Foo foo;

	Bar bar;
    }

does not compile with `lombok 1.16.14` and the 1.16.12.0 `lombok-maven-plugin`.  

> [INFO] --- lombok-maven-plugin:1.16.12.0:delombok (delombok) @ test ---
.../src/main/java/Test.java:7: error: type argument Bar#1 is not within bounds of type-variable Bar#2
@Builder
^
  where Bar#1,Foo,Bar#2 are type-variables:
    Bar#1 extends Set<Foo> declared in class TestBuilder
    Foo extends Object declared in class Test
    Bar#2 extends Set<Foo> declared in class Test
[INFO] Delombok complete.    

However, this class, which is just the output of delombok and some renaming to prevent duplicate class errors, does compile.

    // Generated by delombok at Tue Feb 14 12:08:08 EST 2017

    import java.util.Set;

    interface Inter2<T, U extends Inter2<T, U>> {
    }

    public final class ExpandedTest<Foo, Bar extends Set<Foo>, Quz extends Inter2<Bar, Quz>> {
	    private final Foo foo;
	    private final Bar bar;

	    @java.lang.SuppressWarnings("all")
	    @javax.annotation.Generated("lombok")
	    ExpandedTest(final Foo foo, final Bar bar) {
		    this.foo = foo;
		    this.bar = bar;
	    }

	    @java.lang.SuppressWarnings("all")
	    @javax.annotation.Generated("lombok")
	    public static class ExpandedTestBuilder<Foo, Bar extends Set<Foo>, Quz extends Inter2<Bar, Quz>> {
		    @java.lang.SuppressWarnings("all")
		    @javax.annotation.Generated("lombok")
		    private Foo foo;
		    @java.lang.SuppressWarnings("all")
		    @javax.annotation.Generated("lombok")
		    private Bar bar;

		    @java.lang.SuppressWarnings("all")
		    @javax.annotation.Generated("lombok")
		    ExpandedTestBuilder() {
		    }

		    @java.lang.SuppressWarnings("all")
		    @javax.annotation.Generated("lombok")
		    public ExpandedTestBuilder<Foo, Bar, Quz> foo(final Foo foo) {
			    this.foo = foo;
			    return this;
		    }

		    @java.lang.SuppressWarnings("all")
		    @javax.annotation.Generated("lombok")
		    public ExpandedTestBuilder<Foo, Bar, Quz> bar(final Bar bar) {
			    this.bar = bar;
			    return this;
		    }

		    @java.lang.SuppressWarnings("all")
		    @javax.annotation.Generated("lombok")
		    public ExpandedTest<Foo, Bar, Quz> build() {
			    return new ExpandedTest<Foo, Bar, Quz>(foo, bar);
		    }

		    @java.lang.Override
		    @java.lang.SuppressWarnings("all")
		    @javax.annotation.Generated("lombok")
		    public java.lang.String toString() {
			    return "ExpandedTest.ExpandedTestBuilder(foo=" + this.foo + ", bar=" + this.bar + ")";
		    }
	    }

	    @java.lang.SuppressWarnings("all")
	    @javax.annotation.Generated("lombok")
	    public static <Foo, Bar extends Set<Foo>, Quz extends Inter2<Bar, Quz>> ExpandedTestBuilder<Foo, Bar, Quz> builder() {
		    return new ExpandedTestBuilder<Foo, Bar, Quz>();
	    }

	    @java.lang.SuppressWarnings("all")
	    @javax.annotation.Generated("lombok")
	    public Foo getFoo() {
		    return this.foo;
	    }

	    @java.lang.SuppressWarnings("all")
	    @javax.annotation.Generated("lombok")
	    public Bar getBar() {
		    return this.bar;
	    }

	    @java.lang.Override
	    @java.lang.SuppressWarnings("all")
	    @javax.annotation.Generated("lombok")
	    public boolean equals(final java.lang.Object o) {
		    if (o == this) return true;
		    if (!(o instanceof ExpandedTest)) return false;
		    final ExpandedTest<?, ?, ?> other = (ExpandedTest<?, ?, ?>) o;
		    final java.lang.Object this$foo = this.getFoo();
		    final java.lang.Object other$foo = other.getFoo();
		    if (this$foo == null ? other$foo != null : !this$foo.equals(other$foo)) return false;
		    final java.lang.Object this$bar = this.getBar();
		    final java.lang.Object other$bar = other.getBar();
		    if (this$bar == null ? other$bar != null : !this$bar.equals(other$bar)) return false;
		    return true;
	    }

	    @java.lang.Override
	    @java.lang.SuppressWarnings("all")
	    @javax.annotation.Generated("lombok")
	    public int hashCode() {
		    final int PRIME = 59;
		    int result = 1;
		    final java.lang.Object $foo = this.getFoo();
		    result = result * PRIME + ($foo == null ? 43 : $foo.hashCode());
		    final java.lang.Object $bar = this.getBar();
		    result = result * PRIME + ($bar == null ? 43 : $bar.hashCode());
		    return result;
	    }

	    @java.lang.Override
	    @java.lang.SuppressWarnings("all")
	    @javax.annotation.Generated("lombok")
	    public java.lang.String toString() {
		    return "ExpandedTest(foo=" + this.getFoo() + ", bar=" + this.getBar() + ")";
	    }
    }

Most of the can be removed: the following also compiles.

    import java.util.Set;
    import lombok.Builder;
    import lombok.Value;

    interface Inter<T, U extends Inter<T,U>> {}

    @Builder
    @Value
    public class Test<Foo,
                          Bar extends Set<Foo>,
                      Quz extends Inter<Bar, Quz>>  {

        Foo foo;

        Bar bar;

        public static <Foo, Bar extends Set<Foo>, Quz extends Inter<Bar, Quz>> TestBuilder<Foo, Bar, Quz> builder() {
            return new TestBuilder<Foo, Bar, Quz>();
        }

        public static class TestBuilder<Foo, Bar extends Set<Foo>, Quz extends Inter<Bar, Quz>> {

        }
    }

**Comment by rzwitserloot** [comment]
Succesfully reproduced, notably including @udalrich's remark that you can delombok it, at which point delombok also errors but still produces the output, and said output compiles... just fine. ??? – a weird one.

**Comment by rzwitserloot** [comment]
Fixed.
