### ISSUE TITLE
[BUG] @Delegate fails when targeting certain concrete types

### ISSUE THREAD

**Issue by chrylis** [rzwitserloot/lombok#2569]
**Describe the bug**
When applying `@Delegate` to a field of at least some concrete types, CLI compilation fails with `does not override abstract method`. Compilation in ecj works.

**To Reproduce**
Apply the `@Delegate` annotation to a field of a concrete type implementing an interface implemented by the top-level type. Compile with Maven.

```java
package delegatebug;

import java.util.ArrayList;
import java.util.List;

import lombok.experimental.Delegate;

public final class DelegateBug<E> implements List<E> {

    @Delegate
    private final ArrayList<E> backingList;

    public DelegateBug(List<E> elements) {
        backingList = new ArrayList<>(elements);
    }
}
```

Output:

```
delegatebug/DelegateBug.java:[8,14] delegatebug.DelegateBug is not abstract and does not override abstract method containsAll(java.util.Collection<?>) in java.util.List
```

Note that this is merely the first one that the compiler happened to find; I've had it occur (depending on the vagaries of various hash ordering) on `get(int)` and other methods.

**Expected behavior**
Lombok generates a delegation of `containsAll` to `backingList`.

**Version info (please complete the following information):**
 - 1.18.12
 - Works on ecj 4.17, fails on `openjdk version "11.0.7" 2020-04-14`

**Comment by Rawi01** [comment]
I just created a test case for this one and it seems to work. I checked the history and there was a change related to generic interfaces like in this case. Can you try if it works using the [edge version](https://projectlombok.org/download-edge)?
