### ISSUE TITLE
[Regression] Exception when compiling GWT application with Lombok 1.18.16

### ISSUE THREAD

**Issue by Medo42** [rzwitserloot/lombok#2640]
We have been using Lombok in our GWT application for years now by using the following setting in the gwt-maven-plugin:

`<extraJvmArgs>-javaagent:${lombok.jar.path}=ECJ</extraJvmArgs>`

SuperDevMode also works when giving the same JVM parameter on launch. However, when I try to update to Lombok 1.18.16, I get the following error during the GWT compilation (repeated many times), and the compilation fails:

```
Lombok annotation handler class lombok.eclipse.handlers.HandleGetter failed
java.lang.NoClassDefFoundError: org.eclipse.core.runtime.PlatformObject
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:942)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:535)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:338)
	at lombok.eclipse.handlers.EclipseHandlerUtil.eclipseMode(EclipseHandlerUtil.java:2672)
	at lombok.eclipse.handlers.EclipseHandlerUtil.setDocComment(EclipseHandlerUtil.java:2686)
	at lombok.eclipse.handlers.EclipseHandlerUtil.copyJavadoc(EclipseHandlerUtil.java:2797)
	at lombok.eclipse.handlers.EclipseHandlerUtil.copyJavadoc(EclipseHandlerUtil.java:2764)
	at lombok.eclipse.handlers.HandleGetter.createGetter(HandleGetter.java:299)
	at lombok.eclipse.handlers.HandleGetter.createGetterForField(HandleGetter.java:224)
	at lombok.eclipse.handlers.HandleGetter.generateGetterForField(HandleGetter.java:134)
	at lombok.eclipse.handlers.HandleGetter.generateGetterForType(HandleGetter.java:105)
	at lombok.eclipse.handlers.HandleGetter.handle(HandleGetter.java:161)
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:267)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:107)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:233)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:233)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:226)
	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:224)
	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:185)
	at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:110)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:119)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:190)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:9959)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11136)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11360)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11317)
	at com.google.gwt.dev.javac.JdtCompiler$ParserImpl.parse(JdtCompiler.java:229)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:9732)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:809)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:385)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:428)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1040)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:213)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:192)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:151)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:104)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:666)
	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:810)
	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:551)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:913)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
	at com.google.gwt.dev.DevMode.main(DevMode.java:432)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.runtime.PlatformObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	... 104 more
```
When reverting to Lombok 1.18.12 the problem goes away again.

I tried creating a minimal example, but have not managed to reproduce the issue yet with a minimal GWT application. Maybe someone has an idea about what might cause it anyway, otherwise I'll put in more effort to try creating a reproduction case.

**Comment by rspilker** [comment]
Probably related to #2639

**Comment by Rawi01** [comment]
@rspilker 
The last lombok method in the stacktrace is this one. 
https://github.com/rzwitserloot/lombok/blob/2e35148abe0245427ce579b2afbb36d1496979ed/src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java#L2669-L2678
It catches `Exception` but `NoClassDefFoundError` is an `Error`.

**Comment by Medo42** [comment]
Just confirming that this is still an issue with v1.18.18

**Comment by MCMicS** [comment]
Still no GWT compilation with 1.18.20 if the lombok source is within external jar file
if the source jar contains the delombed versions it works

Try to reproduce it in small sample on sunday/monday

Error: Annotations require @Target for JSR-308 compatibility
```
Annotation types that do not specify explicit target element types cannot be 
applied here
```

With 1.18.10 it works. After upgrade from 1.18.10 to 1.18.12 it was firstly broken for poject source files and after 1.18.20 only for jar source files.

**Comment by Medo42** [comment]
I think this may be a different issue. Even if it's not, it may be easier to file it as a new issue than to get attention to have this one re-opened. You can reference this issue if you think it's related, of course.

For me, things are working again with the fix in 1.18.20, but I'm not compiling lombok-enriched sources out of source jars in my build process.

**Comment by MCMicS** [comment]
I create an bew issue if i create the sample to reproduce it
