### ISSUE TITLE
[BUG] Cannot use 'val' here because... representable type after upgrade to 1.18.10

### ISSUE THREAD

**Issue by pzygielo** [rzwitserloot/lombok#2230]
**Describe the bug**
Upgrade from 18.8 to 18.10 causes compilation error:
> Cannot use 'val' here because initializer expression does not have a representable type: Type cannot be resolved

**To Reproduce**
With two below files `A.java` and `B.java`:

```java
import lombok.*;
import lombok.experimental.*;

@RequiredArgsConstructor(staticName = "of")
public class A {
  @Wither
  private final String a;
}
```
```java
import lombok.*;

public class B {
  public void f() {
    val a = A.of("B");
    val b = a.withA("tr");
  }
}
```
Results:
```
$ javac -cp ~/.m2/repository/org/projectlombok/lombok/1.18.8/lombok-1.18.8.jar B.java A.java 
$
```
and
```
javac -cp ~/.m2/repository/org/projectlombok/lombok/1.18.10/lombok-1.18.10.jar B.java A.java 
B.java:6: error: Cannot use 'val' here because initializer expression does not have a representable type: Type cannot be resolved
    val b = a.withA("tr");
        ^
1 error
```

**Expected behavior**
At most - warning about deprecated `@Wither`.

**Version info (please complete the following information):**
 - Lombok 1.18.10
 - Platform: javac - javac 1.8.0_222
