### ISSUE TITLE
migration to spring boot 2.0.0.release breaks val

### ISSUE THREAD

**Issue by mmczhukov** [rzwitserloot/lombok#1598]
After migrating from spring boot 1.5.10 to spring boot 2.0.0 all vals got broken with message "Cannot use 'val' here because initializer expression does not have a representable type: Type cannot be resolved"

**Comment by pedegie** [comment]
[INFO] --- lombok-maven-plugin:1.16.20.0:delombok (default) @ rest-api ---
D:\zielen-project\rest-api\src\main\java\api\ApiApplication.java:5: error: package org.springframework.boot.autoconfigure.security.servlet does not exist
import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
                                                              ^
D:\zielen-project\rest-api\src\main\java\api\product\domain\exception\ProductException.java:7: error: cannot find symbol
import org.springframework.lang.Nullable;
                               ^
  symbol:   class Nullable
  location: package org.springframework.lang
D:\zielen-project\rest-api\src\main\java\api\ApiApplication.java:7: error: cannot find symbol
@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
                                  ^
  symbol: class SecurityAutoConfiguration
[INFO] Delombok complete.

I have also these bugs after updating to 2.0.0

**Comment by johnaoss** [comment]
@pedegie @mmczhukov Are you two still having this problem?

Some more details are needed: what version of Java and Spring Boot are you on? A pom.xml example would also be helpful.
