### ISSUE TITLE
[BUG][REGRESSION] Unable to manually override Builder.build() methods

### ISSUE THREAD

**Issue by nbali** [rzwitserloot/lombok#2061]
**Describe the bug**
The build() methods on builders was replaceable manually. It's not anymore.

**To Reproduce**
```java
public class BuilderRegressionTest {
    
    public static void main(String[] args) {
        Test.builder().build();
    }
    
    @Builder
    public static class Test {
        
        private String foo;
        
        public static class TestBuilder {
            public Test build() {
                return new Test(foo);
            }
        }
    }
    
}
```

```
$ javac -cp lombok.jar BuilderRegressionTest.java
BuilderRegressionTest.java:11: error: method build() is already defined in class TestBuilder
    @Builder
    ^
1 error
```
**Expected behavior**
This was a maybe a hacky, but an easy way to add extra preparation or validation before the object has been created. It should be still possible to do it.

**Version info (please complete the following information):**
 - Lombok version: 1.18.6 (works on 1.18.4)
 - Java version: 1.8.0_191

**Comment by Paramood** [comment]
Duplicate of #2050
