### ISSUE TITLE
1.18.14 breaks @Delegate

### ISSUE THREAD

**Issue by lprimak** [rzwitserloot/lombok#2610]
**Describe the bug**
Code with `@Delegate` is now broken, works in 1.18.12 

**To Reproduce**
```
git clone https://github.com/flowlogix/flowlogix
edit flowlogix-bom/pom.xml to change lombok version from .12 to .14
mvn package
```
**Expected behavior**
expected to compile

**Version info (please complete the following information):**
mac / maven / Java 8 (latest)

**Additional context**
Compile error:
The method below is a delegated method, and it is not generated anymore by Lombok
```
[ERROR] /Users/lprimak/Documents/devel/flowlogix/jakarta-ee/flowlogix-jee/src/main/java/com/flowlogix/jeedao/impl/TypedNativeQueryImpl.java:[30,8] com.flowlogix.jeedao.impl.TypedNativeQueryImpl is not abstract and does not override abstract method <T>unwrap(java.lang.Class<T>) in javax.persistence.Query
```

**Comment by Rawi01** [comment]
You added `excludes = TypedNativeQuery.class` and `TypedNativeQuery` implements `Query`, I think thats why `@Delegate` does not add the method. The detection of methods in supertypes was improved so it might be possible that lombok now properly find this method and exclude it.

Lombok 1.18.14 should now also detect if the method is already implemented and skip that one. In your case removing the `excludes` should help (haven't tried it).

**Comment by lprimak** [comment]
That worked
However, since this is a breaking change, I believe two things should happen:
- some kind of changelog
- better error message when that happens
